(define (rot-hole theta)
  (insert
   (translate -1 -.7 0)
   (rotz theta)
   (translate 1 .7 0)))

(define black (color .15 .15 .15))
(define black-light (color .2 .2 .2))
(define gray (color .85 .85 .85))
(define yellow (color 1 1 0))

(define (pieces-1 . args)
  (union
    (legopiece-technic-brick-with-holes 4 black)
    (legopiece-technic-brick-with-holes 6 black (translate 2 0 1))
    (legopiece-technic-brick-with-holes 10 black (translate 5 0 2))
    (legopiece-technic-brick-with-holes 4 black (translate 12 0 1))
    (legopiece-plate 1 2 yellow (translate 0 1.2 0))
    (legopiece-plate 2 2 yellow (translate 2 1.2 0))
    (legopiece-plate 1 2 yellow (translate 2 1.6 0))
    (legopiece-plate 2 1 yellow (translate 3 1.6 0))
    (legopiece-technic-pin black-light (translate 2 0 1))
    (legopiece-technic-pin black-light (translate 5 0 2))
    (legopiece-technic-pin gray (translate 6 0 2))
    (legopiece-technic-pin black-light (translate 8 0 2))
    (legopiece-technic-pin black-light (translate 10 0 2))
    (legopiece-technic-pin gray (translate 12 0 2))
    (legopiece-technic-pin black-light (translate 13 0 2))
    (bbox (scale 16 2.2 3))
    (apply insert args)))

(define (pieces-2 . args)
  (union
    (legopiece-technic-brick-with-holes 6 yellow)
    (legopiece-plate 1 2 yellow (translate 0 1.2 0))
    (legopiece-plate 1 2 yellow (translate 0 1.6 0))
    (legopiece-plate 1 2 yellow (translate 4 1.2 0))
    (legopiece-plate 1 2 yellow (translate 4 1.6 0))
    (legopiece-technic-brick-with-holes 8 yellow (translate 0 2 0))
    (legopiece-technic-pin black-light (translate 4 2 1))
    (legopiece-technic-pin black-light (translate 6 2 1))
    (bbox (scale 8 3.4 2))
    (apply insert args)))

(define (pieces-3 . args)
  (union
    (legopiece-technic-brick-with-holes 2 black)
    (legopiece-technic-brick-with-holes 2 black (translate 0 0 3))
    (legopiece-technic-brick-with-holes 2 black (roty pi/2) (translate 0 0 3))
    (legopiece-technic-brick-with-holes 2 black (roty pi/2) (translate 1 0 3))
    (legopiece-technic-plate-with-holes 4 black (roty pi/2) (translate 0 -.4 4))
    (legopiece-technic-plate-with-holes 4 black (roty pi/2) (translate 0 1.2 4))
    (legopiece-technic-pin gray)
    (legopiece-technic-pin gray (translate 0 0 4))
    (legopiece-technic-pin gray (roty pi/2) (translate 0 0 3))
    (legopiece-technic-pin gray (roty pi/2) (translate 2 0 3))
    (bbox (scale 4 2.2 6) (translate -1 -.4 -1))
    (apply insert args)))

(define (pieces-4 . args)
  (union
    (legopiece-technic-brick-with-holes 4 yellow (roty pi/2) (translate 0 .4 2))
    (legopiece-technic-brick-with-holes 6 yellow (translate 0 1.6 1))
    (legopiece-technic-brick-with-holes 6 yellow (translate 0 1.6 -2))
    (legopiece-technic-plate-with-holes 4 yellow (roty pi/2) (translate 0 0 2))
    (bbox (translate 0 0 -.5) (scale 6 3 4))
    (apply insert args)))

(define (pieces-5 . args)
  (union
   (legopiece-technic-brick-with-holes 2 yellow)
   (legopiece-plate 1 2 yellow (translate 0 1.2 0))
   (legopiece-plate 1 2 yellow (translate 0 1.6 0))
   (legopiece-plate 2 1 yellow (translate 0 1.6 0))
   (legopiece-technic-brick-with-holes 6 yellow (translate -2 2 0))
   (legopiece-technic-pin gray (translate -2 2 0))
   (legopiece-technic-pin black-light (translate 2 2 0))
   (bbox (scale 6 3.4 3) (translate -2 0 -1))
   (apply insert args)))

(define (pieces-6 . args)
  (union
   (legopiece-technic-brick-with-holes 6 yellow (translate 0 0 2))
   (legopiece-technic-brick-with-holes 6 yellow (translate 0 0 -3))
   (apply insert args)))

(define (airplane . args)
  (union
    (pieces-1 (translate 0 0 1))
    (pieces-2 (rot-hole pi/2) (translate 10 0 2))
    (pieces-1 (scale 1 1 -1) (translate 0 0 -1))
    (pieces-2 (scale 1 1 -1) (rot-hole pi/2) (translate 10 0 -2))
    (pieces-4 (translate -1 1.6 0))
    (pieces-3 (translate 10 2 -2))
    (pieces-5 (translate 8 4 3))
    (pieces-5 (scale 1 1 -1) (translate 8 4 -3))
    (pieces-6 (translate -5 -.7 0) (rotz .7509279107) (translate 7 6.7 0))
    (apply insert args)))
