(define (rot-hole)
  (insert
;;    (translate -.5 -.35 0)
   (translate (- lu) (* .7 lu) 0)
   (rotz pi/2)
   (translate lu (* .7 lu) 0)))
;;   (translate .5 .35 0)))

(define (pieces-1 . args)
  (union
    (legopiece-technic-brick-with-holes 4)
    (legopiece-technic-brick-with-holes 6 (translate 1 0 .5))
    (legopiece-technic-brick-with-holes 10 (translate 2.5 0 1))
    (legopiece-technic-brick-with-holes 4 (translate 6 0 .5))
    (legopiece-plate 1 2 (translate 0 .6 0))
    (legopiece-plate 2 2 (translate 1 .6 0))
    (legopiece-plate 1 2 (translate 1 .8 0))
    (legopiece-plate 2 1 (translate 1.5 .8 0))
    (legopiece-technic-pin (translate 1 0 .5))
    (legopiece-technic-pin (translate 2.5 0 1))
    (legopiece-technic-pin (translate 3 0 1))
    (legopiece-technic-pin (translate 4 0 1))
    (legopiece-technic-pin (translate 5 0 1))
    (legopiece-technic-pin (translate 6 0 1))
    (legopiece-technic-pin (translate 6.5 0 1))
    (bbox (scale 8 1.1 1.5))
    (apply insert args)))

(define (pieces-2 . args)
  (union
    (legopiece-technic-brick-with-holes 6)
    (legopiece-plate 1 2 (translate 0 .6 0))
    (legopiece-plate 1 2 (translate 0 .8 0))
    (legopiece-plate 1 2 (translate 2 .6 0))
    (legopiece-plate 1 2 (translate 2 .8 0))
    (legopiece-technic-brick-with-holes 8 (translate 0 1.0 0))
    (legopiece-technic-pin (translate 2 1 .5))
    (legopiece-technic-pin (translate 3 1 .5))
    (bbox (scale 4 1.7 1))
    (apply insert args)))

(define (pieces-3 . args)
  (union
    (legopiece-technic-brick-with-holes 2)
    (legopiece-technic-brick-with-holes 2 (translate 0 0 1.5))
    (legopiece-technic-brick-with-holes 2 (roty (/ pi 2)) (translate 0 0 1.5))
    (legopiece-technic-brick-with-holes 2 (roty (/ pi 2)) (translate .5 0 1.5))
    (legopiece-technic-plate-with-holes 4 (roty (/ pi 2)) (translate 0 (- .2) 2))
    (legopiece-technic-plate-with-holes 4 (roty (/ pi 2)) (translate 0 .6 2))
    (legopiece-technic-pin)
    (legopiece-technic-pin (translate 0 0 2))
    (legopiece-technic-pin (roty (/ pi 2)) (translate 0 0 1.5))
    (legopiece-technic-pin (roty (/ pi 2)) (translate 1 0 1.5))
    (bbox (scale 2 1.1 3) (translate -.5 -.2 -.5))
    (apply insert args)))

(define (pieces-4 . args)
  (union
    (legopiece-technic-brick-with-holes 4 (roty (/ pi 2)) (translate 0 .2 1))
    (legopiece-technic-brick-with-holes 6 (translate 0 .8 .5))
    (legopiece-technic-brick-with-holes 6 (translate 0 .8 -1))
    (legopiece-technic-plate-with-holes 4 (roty (/ pi 2)) (translate 0 0 1))
    (bbox (translate 0 0 -.5) (scale 3 1.5 2))
    (apply insert args)))

(define (airplane . args)
  (union
    (pieces-1 (translate 0 0 .5))
    (pieces-2 (rot-hole) (translate 5 0 1))
    (pieces-1 (scale 1 1 -1) (translate 0 0 -.5))
    (pieces-2 (scale 1 1 -1) (rot-hole) (translate 5 0 -1))
    (pieces-4 (translate -.5 .8 0))
    (pieces-3 (translate 5 1 -1))
    (apply insert args)))
