(define (rot-hole)
  (insert
   (translate -1 -.7 0)
   (rotz pi/2)
   (translate 1 .7 0)))

(define (pieces-1 . args)
  (union
    (legopiece-technic-brick-with-holes 4)
    (legopiece-technic-brick-with-holes 6 (translate 2 0 1))
    (legopiece-technic-brick-with-holes 10 (translate 5 0 2))
    (legopiece-technic-brick-with-holes 4 (translate 12 0 1))
    (legopiece-plate 1 2 (translate 0 1.2 0))
    (legopiece-plate 2 2 (translate 2 1.2 0))
    (legopiece-plate 1 2 (translate 2 1.6 0))
    (legopiece-plate 2 1 (translate 3 1.6 0))
    (legopiece-technic-pin (translate 2 0 1))
    (legopiece-technic-pin (translate 5 0 2))
    (legopiece-technic-pin (translate 6 0 2))
    (legopiece-technic-pin (translate 8 0 2))
    (legopiece-technic-pin (translate 10 0 2))
    (legopiece-technic-pin (translate 12 0 2))
    (legopiece-technic-pin (translate 13 0 2))
    (bbox (scale 16 2.2 3))
    (apply insert args)))

(define (pieces-2 . args)
  (union
    (legopiece-technic-brick-with-holes 6)
    (legopiece-plate 1 2 (translate 0 1.2 0))
    (legopiece-plate 1 2 (translate 0 1.6 0))
    (legopiece-plate 1 2 (translate 4 1.2 0))
    (legopiece-plate 1 2 (translate 4 1.6 0))
    (legopiece-technic-brick-with-holes 8 (translate 0 2 0))
    (legopiece-technic-pin (translate 4 2 1))
    (legopiece-technic-pin (translate 6 2 1))
    (bbox (scale 8 3.4 2))
    (apply insert args)))

(define (pieces-3 . args)
  (union
    (legopiece-technic-brick-with-holes 2)
    (legopiece-technic-brick-with-holes 2 (translate 0 0 3))
    (legopiece-technic-brick-with-holes 2 (roty pi/2) (translate 0 0 3))
    (legopiece-technic-brick-with-holes 2 (roty pi/2) (translate 1 0 3))
    (legopiece-technic-plate-with-holes 4 (roty pi/2) (translate 0 -.4 4))
    (legopiece-technic-plate-with-holes 4 (roty pi/2) (translate 0 1.2 4))
    (legopiece-technic-pin)
    (legopiece-technic-pin (translate 0 0 4))
    (legopiece-technic-pin (roty pi/2) (translate 0 0 3))
    (legopiece-technic-pin (roty pi/2) (translate 2 0 3))
    (bbox (scale 4 2.2 6) (translate -1 -.4 -1))
    (apply insert args)))

(define (pieces-4 . args)
  (union
    (legopiece-technic-brick-with-holes 4 (roty pi/2) (translate 0 .4 2))
    (legopiece-technic-brick-with-holes 6 (translate 0 1.6 1))
    (legopiece-technic-brick-with-holes 6 (translate 0 1.6 -2))
    (legopiece-technic-plate-with-holes 4 (roty pi/2) (translate 0 0 2))
    (bbox (translate 0 0 -.5) (scale 6 3 4))
    (apply insert args)))

(define (airplane . args)
  (union
    (pieces-1 (translate 0 0 1))
    (pieces-2 (rot-hole) (translate 10 0 2))
    (pieces-1 (scale 1 1 -1) (translate 0 0 -1))
    (pieces-2 (scale 1 1 -1) (rot-hole) (translate 10 0 -2))
    (pieces-4 (translate -1 1.6 0))
    (pieces-3 (translate 10 2 -2))
    (apply insert args)))
